import { combineReducers } from "redux"
import settings from "./settings"
import demographics from "./demographics"
import user from "./user"
import client from "./client"
import auth from "./auth"
import currentSessionUser from "./client"
import filter from "./filter"
import {
  userManagementDepartments,
  userManagementLocations,
  userManagementUsers,
  userManagementDomainHeader,
  CampaignBasicBufferAllData,
  CampaignBufferCommentAllData,
  CampaignBufferRatesAllData,
  CampaignCommentAllData,
  CampaignStatsAllData,
  CampaignRatesAllData,
  CampaignBarAllData,
  CampaignHeatAllData,
  CampaignHeatBufferAllData,
  campaignMain,
  campaignMainByID,
  clientsManagement,
  surveysManagement,
  getPreferencesDemographic,
  sendPreferencesDemographic,
  toggleEnableDepartment,
  getLocationFloorData,
  getFloorData,
  helpDeskGetData,
  getlocationGroupList,
  getLocationData,
  locationListData,
  getNotificationManagement,
  exportClients,
  saveClientsMainSettings,
  updateClientsMainSettings,
  dropdownDepartments,
  getSurveySetupData,
  getOtherSurveySetupData,
  getSurveysLanguages,
  getAllLanguages,
  getSurveysMetrics,
  getClientLocations,
  getClientUsers,
  getDomainVerificationData,
  deleteSelectedClient,
  getClientIndustry,
  getAdditionalModules,
  getSelectedModules,
  getSelectedPages,
  getSelectedQuestions,
  setSurveySetupFormData,
  setSurveySetupDrawerData,
  setSurveySetupGeneralData,
  postNewLocation,
  updateLocation,
  setSelectedSurveyStatusData,
  getRegions,
  getCountries,
  getCities,
  getV2Client,
} from "./adminReducers.js"
import {
  campaignDetailsReducer,
  campaignsGraf,
  campaignsReducer,
  bufferCampaignsReducer,
  feedbackCommentsViewReducer,
  feedbackClientDataViewReducer,
  feedbackJoinDataViewReducer,
  feedBackResult,
  feedBackThemeView,
  regionsGlobal,
  campaignClosedDetails,
  results,
  waveEngagement,
  xpScore,
  newSurveyHomeReducer,
} from "./clientReducers"

import {
  saveClientIdForSurveys,
  saveMenuIndex,
  saveMenuIndexSub,
  saveRowData,
  saveEditOrCreateClient,
} from "./clientManagement.js"

import { saveSurveyId, saveClientName } from "./surveysManagement"

import { leesmanClient, leesmanLogs, leesmanMigration } from "./leesmanReducer"
export default combineReducers({
  currentSessionUser,
  settings,
  demographics,
  user,
  client,
  clientsManagement,
  auth,
  filter,
  campaignsGraf,
  userManagementDepartments,
  userManagementLocations,
  userManagementUsers,
  userManagementDomainHeader,
  CampaignBasicBufferAllData,
  CampaignBufferCommentAllData,
  CampaignBufferRatesAllData,
  CampaignCommentAllData,
  CampaignStatsAllData,
  CampaignRatesAllData,
  CampaignBarAllData,
  CampaignHeatAllData,
  CampaignHeatBufferAllData,
  campaignDetailsReducer,
  campaignsReducer,
  bufferCampaignsReducer,
  feedbackCommentsViewReducer,
  feedbackClientDataViewReducer,
  feedbackJoinDataViewReducer,
  feedBackResult,
  feedBackThemeView,
  regionsGlobal,
  campaignClosedDetails,
  results,
  waveEngagement,
  xpScore,
  newSurveyHomeReducer,
  campaignMain,
  campaignMainByID,
  leesmanClient,
  leesmanLogs,
  leesmanMigration,
  getPreferencesDemographic,
  sendPreferencesDemographic,
  toggleEnableDepartment,
  getLocationFloorData,
  getFloorData,
  helpDeskGetData,
  getlocationGroupList,
  getLocationData,
  locationListData,
  getNotificationManagement,
  exportClients,
  saveClientsMainSettings,
  updateClientsMainSettings,
  surveysManagement,
  dropdownDepartments,
  getSurveySetupData,
  getOtherSurveySetupData,
  saveMenuIndex,
  saveClientIdForSurveys,
  saveMenuIndexSub,
  getSurveysLanguages,
  saveSurveyId,
  getAllLanguages,
  saveClientName,
  saveRowData,
  saveEditOrCreateClient,
  getSurveysMetrics,
  getClientLocations,
  getClientUsers,
  getDomainVerificationData,
  deleteSelectedClient,
  getClientIndustry,
  getAdditionalModules,
  getSelectedModules,
  getSelectedPages,
  getSelectedQuestions,
  setSurveySetupFormData,
  setSurveySetupDrawerData,
  setSurveySetupGeneralData,
  postNewLocation,
  updateLocation,
  setSelectedSurveyStatusData,
  getRegions,
  getCountries,
  getCities,
  getV2Client,
})
